baseurl = "http://www.copenhagenmusic.dk/"
canonifyurls = false
copyright = "Open Source under the MIT license."
disableKinds = ["404", "taxonomyTerm", "taxonomy"]
enableEmoji = true
googleAnalytics = ""
DefaultContentLanguage = "en"
paginate = 10
relativeurls = false
theme = "startbootstrap-clean-blog"
title = "Copenhagen Music"
[author]
name = "Copenhagen Music"
[[menu.main]]
identifier = "home"
name = "Forside"
url = "/"
weight = 1
[params]
dateform = "Mon, Jan 2, 2006"
description = ""
addressLine = "Copenhagen Musik address line"
email = "info@copenhagenmusic.dk"
image = "/uploads/2018/01/01/unsplash-garrett-parker-247225.jpg"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/copenhagenmusic.dk"
[taxonomies]
category = "categories"
tag = "tags"
