baseurl = "http://www.copenhagenmusic.dk/"
canonifyurls = false
copyright = "Open Source under the MIT license."
disableKinds = ["404", "taxonomyTerm", "taxonomy"]
enableEmoji = true
googleAnalytics = ""
DefaultContentLanguage = "da"
paginate = 10
relativeurls = false
theme = "startbootstrap-clean-blog"
title = "Copenhagen Music"
[author]
name = "Copenhagen Music"
[languages]
[languages.da]
weight = 1
languageName = "Dansk"
[[languages.da.menu.main]]
identifier = "home"
url = "/"
name = "Forside"
weight = 1
[languages.en]
weight = 2
languageName = "English"
[[languages.en.menu.main]]
identifier = "home"
url = "/"
name = "Home"
weight = 1
[params]
addressline = "Julius Andersens Vej 9, 2450 København SV"
dateform = "Mon, Jan 2, 2006"
description = ""
email = "info@copenhagenmusic.dk"
image = "/uploads/2018/04/12/CopenhagenMusicCoverPhoto.png"
[[params.social]]
title = "facebook"
url = "https://www.facebook.com/copenhagenmusic.dk"
[taxonomies]
category = "categories"
tag = "tags"
