---
label: default
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: subtitle
  label: Subtitle
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
- name: imageVertAlign
  label: Image Centering
  type: text
  hidden: false
  default: '50'
- name: type
  label: Type
  type: text
  hidden: true
  default: page
pages:
- hugo/content/_index.en.md
- hugo/content/_index.md
- hugo/content/ledelsesgruppen.md
- hugo/content/om.en.md
- hugo/content/om.md
