---
pages:
- _index.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- type: text
  name: subtitle
  label: Subtitle
  default: ''
- name: image
  label: Image
  type: file
  hidden: false
  default: ''
  - name: imageVertAlign
  label: Image Centering
  type: number
  hidden: false
  config:
    min: '0'
    max: '100'
  default: '50'
- name: type
  label: Type
  type: text
  hidden: true
  default: page