---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url:
sections:
- type: directory
  path: hugo/content
  label: Pages
  create: all
  match: "*"
- type: directory
  path: hugo/content/ensemble
  label: Ensemble
  create: all
  match: "**/*"
upload_dir: hugo/static/uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":year:/:month:/:day:/:filename:"
instant_preview: false
build:
  preview_env:
  - HUGO_ENV=staging
  - HUGO_VERSION=0.52
  - BUILD_DIR=hugo
  preview_output_directory: hugo/public
  preview_docker_image: forestryio/build:latest
  mount_path: "/opt/buildhome/repo"
  instant_preview_command: hugo server -D -E -F --port 8080 --bind 0.0.0.0 --renderToDisk
    -d public
  publish_command: hugo -d public
  publish_env:
  - HUGO_ENV=production
  - HUGO_VERSION=0.52
  output_directory: public
  preview_command: hugo -E -F -D -b $DEPLOY_URL -d public
version: 0.52
